name: agri_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

scripts:
  gen: "flutter pub run build_runner watch --delete-conflicting-outputs"
  slang: "dart run slang"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_flavorizr: ^2.2.1
  flutter_riverpod: ^2.3.6
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  hive_flutter: ^1.1.0
  auto_route: ^7.7.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  dartz: ^0.10.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  intl: ^0.18.0
  flutter_form_builder: ^9.1.0
  slang: ^3.22.0
  slang_flutter: ^3.22.0
  flutter_localization: ^0.1.13
  path_provider: ^2.0.15
  smooth_page_indicator: ^1.1.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  weather: ^3.1.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  hive_generator: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  auto_route_generator: ^7.2.0
  slang_build_runner: ^3.22.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/app_icons/
    - assets/i18n/
    - .env.dev
    - .env.prod

  fonts:
    - family: "SVNPoppins"
      fonts:
        - asset: assets/fonts/SVN-Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/SVN-Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/SVN-Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SVN-Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/SVN-Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/SVN-Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/SVN-Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SVN-Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/SVN-Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SVN-Poppins-Black.ttf
          weight: 900
    - family: AppIcons
      fonts:
        - asset: assets/fonts/app_icons.ttf

flutter_gen:
  output: lib/global/gen
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

flavorizr:
  flavors:
    dev:
      app:
        name: "Agri App DEV"
      android:
        applicationId: "com.example.agri_app"
        firebase:
          config: ".firebase/dev/google-services.json"

      ios:
        bundleId: "com.example.agriApp"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"

    prod:
      app:
        name: "Agri App"
      android:
        applicationId: "com.khuaho.agri"
        firebase:
          config: ".firebase/prod/google-services.json"

      ios:
        bundleId: "com.khuaho.agri"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"
