// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-I_l2fzetDNmrykJIcug8ZpooesYSi-8',
    appId: '1:920413736023:web:41543f35cfb019baaa6712',
    messagingSenderId: '920413736023',
    projectId: 'agriapp-c2b55',
    authDomain: 'agriapp-c2b55.firebaseapp.com',
    storageBucket: 'agriapp-c2b55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXxZw-DVEzlzTVGC9WA1Qc-ez9H8TRtvQ',
    appId: '1:920413736023:android:9e2e7ec75de48d50aa6712',
    messagingSenderId: '920413736023',
    projectId: 'agriapp-c2b55',
    storageBucket: 'agriapp-c2b55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG_Juj_TPwA75SizXhJbqgwCz0B29z6Mg',
    appId: '1:920413736023:ios:4d4a190c1111c4a5aa6712',
    messagingSenderId: '920413736023',
    projectId: 'agriapp-c2b55',
    storageBucket: 'agriapp-c2b55.appspot.com',
    iosClientId:
        '920413736023-ssgito61lu9l311gjm6bn0qqdd22riqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG_Juj_TPwA75SizXhJbqgwCz0B29z6Mg',
    appId: '1:920413736023:ios:7a9e09bd797ef3c2aa6712',
    messagingSenderId: '920413736023',
    projectId: 'agriapp-c2b55',
    storageBucket: 'agriapp-c2b55.appspot.com',
    iosClientId:
        '920413736023-20bfjjg1gj6684u60i71cjs3qhk9esoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriApp.RunnerTests',
  );
}
